export const CLIENT_BILLING_CONFIG_REPOSITORY = Symbol('CLIENT_BILLING_CONFIG_REPOSITORY');
export const BILLING_GROUP_REPOSITORY = Symbol('BILLING_GROUP_REPOSITORY');
export const BILLING_GROUP_MEMBER_REPOSITORY = Symbol('BILLING_GROUP_MEMBER_REPOSITORY');
export const INVOICE_REPOSITORY = Symbol('INVOICE_REPOSITORY');
export const INVOICE_LINE_REPOSITORY = Symbol('INVOICE_LINE_REPOSITORY');
export const PAYROLL_COST_SNAPSHOT_REPOSITORY = Symbol('PAYROLL_COST_SNAPSHOT_REPOSITORY');
export const BILLING_PERIOD_CLOSE_REPOSITORY = Symbol('BILLING_PERIOD_CLOSE_REPOSITORY');
