import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1789390244861 implements MigrationInterface {
    name = 'InitialSchema1789390244861'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // uuid PKs default to uuid_generate_v4(); ensure the extension exists on
        // hosts whose template database does not ship it (managed Postgres).
        // Deliberately not dropped in down() — other schemas may rely on it.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "approval_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "subjectType" character varying(64) NOT NULL, "subjectId" uuid NOT NULL, "requestedByUserId" uuid NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "decidedByUserId" uuid, "decisionNote" text, CONSTRAINT "PK_484806bb8ff331b851fc75973c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f45df3f8c6cb9dc8b6573e2c2" ON "approval_requests" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_36db0e967a26420d3f33eeea18" ON "approval_requests" ("organizationId", "status") `);
        await queryRunner.query(`CREATE TABLE "processed_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "consumerName" character varying(128) NOT NULL, "eventId" uuid NOT NULL, "processedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_a08d68aa0747daea9efd2ddea53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3441394ea68b33d494a4de1e8" ON "processed_events" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_30487a0b7614c9b0b3ea84b8b6" ON "processed_events" ("consumerName", "eventId") `);
        await queryRunner.query(`CREATE TABLE "outbox_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "eventName" character varying(128) NOT NULL, "payload" jsonb NOT NULL, "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, "version" integer NOT NULL DEFAULT '1', "status" character varying(16) NOT NULL DEFAULT 'pending', "attempts" integer NOT NULL DEFAULT '0', "processedAt" TIMESTAMP WITH TIME ZONE, "lastError" text, CONSTRAINT "PK_0171348f527c64b137e4d4f5b66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_698397478208a19b887d555da0" ON "outbox_messages" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_702a378b99f32d7a67da415f4b" ON "outbox_messages" ("status", "occurredAt") `);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(256) NOT NULL, "contentType" character varying(128) NOT NULL, "storageKey" character varying(512) NOT NULL, "sizeBytes" bigint NOT NULL DEFAULT '0', "classification" character varying(16) NOT NULL DEFAULT 'internal', CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f16eaa571c8fc0ee214cad0f1c" ON "documents" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "document_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "documentId" uuid NOT NULL, "versionNumber" integer NOT NULL, "storageKey" character varying(512) NOT NULL, "contentType" character varying(128) NOT NULL, "sizeBytes" bigint NOT NULL DEFAULT '0', "signatureStatus" character varying(24) NOT NULL DEFAULT 'notRequired', "signedAt" TIMESTAMP WITH TIME ZONE, "signatureProvider" character varying(80), "externalEnvelopeId" character varying(160), "createdByUserId" uuid, CONSTRAINT "PK_baf26dab035c6d6fc433f9dc6a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9ca925f66775b959124999155f" ON "document_versions" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_24fbd55f077dc6f373c0b7030c" ON "document_versions" ("organizationId", "documentId", "versionNumber") `);
        await queryRunner.query(`CREATE TABLE "user_role_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "userId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_ac634a3aa59d70bf0fb7b423b47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0286ef461cd5bf71cd6fa29d52" ON "user_role_assignments" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5297b03c43166a7a7543fda0f2" ON "user_role_assignments" ("organizationId", "userId", "roleId") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "key" character varying(64), "name" character varying(64) NOT NULL, "permissions" jsonb NOT NULL DEFAULT '[]', "dataScope" character varying(16) NOT NULL DEFAULT 'own', CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0933e1dfb2993d672af1a98f08" ON "roles" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c63f25e362340df593c13fb152" ON "roles" ("organizationId", "key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d27a5e69fb41256abed347a85e" ON "roles" ("organizationId", "name") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "email" character varying(320) NOT NULL, "passwordHash" character varying(200) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'invited', "mfaEnabled" boolean NOT NULL DEFAULT false, "isWorkspaceCreator" boolean NOT NULL DEFAULT false, "employeeId" uuid, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f3d6aea8fcca58182b2e80ce97" ON "users" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7191f881489123fab6c8e5273" ON "users" ("employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ddfb7904324cdba38d3c73de93" ON "users" ("organizationId", "email") `);
        await queryRunner.query(`CREATE TABLE "audit_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "actorUserId" uuid, "action" character varying(64) NOT NULL, "resourceType" character varying(64) NOT NULL, "resourceId" character varying(64) NOT NULL, "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, "before" jsonb, "after" jsonb, "metadata" jsonb, CONSTRAINT "PK_910f64d901a5c3e9878f0d4a407" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f2c9619322e5354049f139a3d" ON "audit_events" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_52601717ed17e30ae08b90993b" ON "audit_events" ("organizationId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b81fec571ea2be3b498f7bc96" ON "audit_events" ("resourceType", "resourceId") `);
        await queryRunner.query(`CREATE TABLE "shortlists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "jobPostingId" uuid NOT NULL, "roundNumber" integer NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'draft', "presentedAt" TIMESTAMP WITH TIME ZONE, "closedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cef7d8cee850bbdd9205a9dcd46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d08f805c2826a6a503ae3823b6" ON "shortlists" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c65a0cb7235f739e2010d70999" ON "shortlists" ("organizationId", "jobPostingId", "roundNumber") `);
        await queryRunner.query(`CREATE TABLE "shortlist_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "shortlistId" uuid NOT NULL, "applicationId" uuid NOT NULL, "rank" integer NOT NULL, "clientDecision" character varying(16) NOT NULL DEFAULT 'pending', "clientNote" text, "decidedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ea78584da6e635c91c786064234" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af8dcab806f3298e6072e3e532" ON "shortlist_entries" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d1011d56e572cb38134245cce6" ON "shortlist_entries" ("organizationId", "shortlistId", "applicationId") `);
        await queryRunner.query(`CREATE TABLE "offers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "applicationId" uuid NOT NULL, "baseSalary" numeric(14,2) NOT NULL, "salaryCurrency" character varying(3) NOT NULL, "startDate" date NOT NULL, "probationDays" integer, "noticePeriodDays" integer, "extras" jsonb NOT NULL DEFAULT '[]', "status" character varying(16) NOT NULL DEFAULT 'draft', "sentAt" TIMESTAMP WITH TIME ZONE, "respondedAt" TIMESTAMP WITH TIME ZONE, "hiredEmployeeId" uuid, "notes" text, CONSTRAINT "PK_4c88e956195bba85977da21b8f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_531330d7396291798408abcc80" ON "offers" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0c239940681cf027f38584987" ON "offers" ("organizationId", "applicationId") `);
        await queryRunner.query(`CREATE TABLE "interviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "applicationId" uuid NOT NULL, "interviewRoundId" uuid NOT NULL, "scheduledAt" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'scheduled', "outcome" character varying(16), "notes" text, "scheduledByUserId" uuid NOT NULL, CONSTRAINT "PK_fd41af1f96d698fa33c2f070f47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8cf1a0367209ecf220b3ff78bf" ON "interviews" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c0f5447cbeddb1f62427d38c3" ON "interviews" ("organizationId", "applicationId") `);
        await queryRunner.query(`CREATE TABLE "job_postings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "sourceHiringRequestId" uuid NOT NULL, "sourceOrganizationId" uuid NOT NULL, "title" character varying(200) NOT NULL, "slug" character varying(220) NOT NULL, "description" text, "salaryMin" numeric(14,2), "salaryMax" numeric(14,2), "salaryCurrency" character varying(3), "isPublished" boolean NOT NULL DEFAULT false, "publishSalaryRange" boolean NOT NULL DEFAULT true, "postedAt" TIMESTAMP WITH TIME ZONE, "closesOn" date, CONSTRAINT "PK_dda635ece382c8ad2d90a179182" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af49a547afc9d8e9f790057a9c" ON "job_postings" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5da82c4d774cc1fcaf5d361da0" ON "job_postings" ("organizationId", "slug") `);
        await queryRunner.query(`CREATE TABLE "interview_panel_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "interviewId" uuid NOT NULL, "userId" uuid, "externalName" character varying(200), "externalEmail" character varying(320), CONSTRAINT "PK_7d4d067f5daa27eea4c79273c31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5bdf1b036b1da2a8443cfee6fa" ON "interview_panel_members" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_425f9fc0d8290a4d6325fc98d2" ON "interview_panel_members" ("organizationId", "interviewId") `);
        await queryRunner.query(`CREATE TABLE "interview_rounds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(120) NOT NULL, "orderIndex" integer NOT NULL DEFAULT '0', "skills" jsonb NOT NULL DEFAULT '[]', "expectedRating" numeric(3,1), CONSTRAINT "PK_8b3eabbc6733b67b32955f51f83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cfa3b50494400d9b68eded6b3" ON "interview_rounds" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6d309e56d27155e455b23a1e53" ON "interview_rounds" ("organizationId", "orderIndex") `);
        await queryRunner.query(`CREATE TABLE "interview_feedback_skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "feedbackId" uuid NOT NULL, "skill" character varying(120) NOT NULL, "score" integer NOT NULL, CONSTRAINT "PK_73e3307a010651d148442c818a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f6e541878030a70fd8e16e0b38" ON "interview_feedback_skills" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ba5e954677afd1a83b12dee215" ON "interview_feedback_skills" ("organizationId", "feedbackId", "skill") `);
        await queryRunner.query(`CREATE TABLE "interview_feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "interviewId" uuid NOT NULL, "panelMemberId" uuid NOT NULL, "recordedByUserId" uuid NOT NULL, "overallNote" text, "submittedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "withdrawnAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f8d045feaf71f9a077b36ab6476" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a96087ce438fd97173f59b72e1" ON "interview_feedback" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ba26b5a49c128813199d2e1bb2" ON "interview_feedback" ("organizationId", "interviewId", "panelMemberId") WHERE "withdrawnAt" IS NULL`);
        await queryRunner.query(`CREATE TABLE "hiring_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "positionTitle" character varying(200) NOT NULL, "jobDescription" text, "headcount" integer NOT NULL DEFAULT '1', "employmentType" character varying(16) NOT NULL DEFAULT 'permanent', "location" character varying(200), "preferredStartDate" date, "targetFillDate" date, "salaryMin" numeric(14,2), "salaryMax" numeric(14,2), "salaryCurrency" character varying(3), "hiringManagerEmployeeId" uuid, "reportsToEmployeeId" uuid, "priority" character varying(16) NOT NULL DEFAULT 'normal', "positionId" uuid, "clientNote" text, "tethrNote" text, "status" character varying(24) NOT NULL DEFAULT 'submitted', "requestedByUserId" uuid NOT NULL, "updatedByUserId" uuid, CONSTRAINT "PK_3b8c333952627d2725bb85feba1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1c0280da4d594ccdc92d45566" ON "hiring_requests" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_49195e316cc822e0166fb268e9" ON "hiring_requests" ("organizationId", "status") `);
        await queryRunner.query(`CREATE TABLE "candidates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "fullName" character varying(200) NOT NULL, "email" character varying(320) NOT NULL, "phone" character varying(64), "linkedin" character varying(320), "portfolio" character varying(320), "source" character varying(32) NOT NULL DEFAULT 'form', "consentGivenAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_140681296bf033ab1eb95288abb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d56a47318062e86ca2585103af" ON "candidates" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_06cb3a14600de021f89d1089b0" ON "candidates" ("organizationId", "email") `);
        await queryRunner.query(`CREATE TABLE "hiring_request_updates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "hiringRequestId" uuid NOT NULL, "status" character varying(24) NOT NULL, "actor" character varying(16) NOT NULL, "note" text, "createdByUserId" uuid NOT NULL, CONSTRAINT "PK_86d5f0f80f4fcfe59c4960aebba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5e655dbefaba9ea137d7239f60" ON "hiring_request_updates" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d20a7d106b7e2d197d214997a0" ON "hiring_request_updates" ("organizationId", "hiringRequestId") `);
        await queryRunner.query(`CREATE TABLE "cv_parses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "candidateDocumentId" uuid NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "extractedText" text, "structured" jsonb NOT NULL DEFAULT '{}', "score" numeric(6,2), "provider" character varying(64), "parsedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_93748b215bf24accb6464b67deb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1cb1c49d7ee68613e0db8bab2c" ON "cv_parses" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f1c4b0be2767a20b4f20b04ca2" ON "cv_parses" ("organizationId", "candidateDocumentId") `);
        await queryRunner.query(`CREATE TABLE "candidate_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "candidateId" uuid NOT NULL, "label" character varying(32) NOT NULL DEFAULT 'resume', "versionNumber" integer NOT NULL DEFAULT '1', "storageKey" character varying(512) NOT NULL, "fileName" character varying(255) NOT NULL, "contentType" character varying(128) NOT NULL, "sizeBytes" bigint NOT NULL DEFAULT '0', CONSTRAINT "PK_a7b7572a2c5c1320a4249ce2b4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2593c8a7526e53ad6e424562ce" ON "candidate_documents" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d9970b4876c927276e2f188e15" ON "candidate_documents" ("organizationId", "candidateId", "label", "versionNumber") `);
        await queryRunner.query(`CREATE TABLE "applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "candidateId" uuid NOT NULL, "jobPostingId" uuid NOT NULL, "formSubmissionId" uuid, "stage" character varying(24) NOT NULL DEFAULT 'screening', "outcome" character varying(16) NOT NULL DEFAULT 'active', "onHold" boolean NOT NULL DEFAULT false, "holdReason" text, "expectedSalary" numeric(14,2), "salaryCurrency" character varying(3), "currentSalary" numeric(14,2), "currentTitle" character varying(200), "yearsExperience" integer, "location" character varying(200), "skills" text, "coverNote" text, "manualRating" integer, "notes" text, CONSTRAINT "PK_938c0a27255637bde919591888f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_630548134611c66a73c8b82bc1" ON "applications" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_88d9e9c503051c35643ebfc49d" ON "applications" ("organizationId", "candidateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e46bba20d9b2a0a212c53c8618" ON "applications" ("organizationId", "jobPostingId") `);
        await queryRunner.query(`CREATE TABLE "positions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "title" character varying(200) NOT NULL, "jobId" uuid NOT NULL, "departmentId" uuid, "locationId" uuid, "gradeId" uuid, "status" character varying(16) NOT NULL DEFAULT 'open', "headcount" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_17e4e62ccd5749b289ae3fae6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52017e4e4b745305eaee9313d5" ON "positions" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f12007cfd7db4b8aa269d13e27" ON "positions" ("organizationId", "status") `);
        await queryRunner.query(`CREATE TABLE "pay_bands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "gradeId" uuid NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "minAmount" numeric(14,2) NOT NULL, "maxAmount" numeric(14,2) NOT NULL, CONSTRAINT "PK_54ba1ca57e1e20740ebf177b33d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3624b2ac7912966d338ab9bc0e" ON "pay_bands" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "title" character varying(128) NOT NULL, "jobFamilyId" uuid, CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08bdc8b939f39e6d55b4c38cfb" ON "jobs" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "grades" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "code" character varying(32) NOT NULL, "level" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_4740fb6f5df2505a48649f1687b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ba005a1de94c4e8813351576b" ON "grades" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7f38e5f23d1cfad4261802726" ON "grades" ("organizationId", "code") `);
        await queryRunner.query(`CREATE TABLE "job_families" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(128) NOT NULL, CONSTRAINT "PK_a35b76f2dc2a2e4df914d931fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0caf5ce7c6fe569bdc8365fcf0" ON "job_families" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "kind" character varying(16) NOT NULL DEFAULT 'client', "legalName" character varying(256) NOT NULL, "displayName" character varying(256) NOT NULL, "slug" character varying(280) NOT NULL, "clientId" uuid, "defaultLocale" character varying(8) NOT NULL DEFAULT 'en', "defaultCurrency" character varying(3) NOT NULL DEFAULT 'USD', "settings" jsonb NOT NULL DEFAULT '{}', "brandColor" character varying(16) NOT NULL DEFAULT 'iris', CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3b1aee57d246d82c531016e652" ON "organizations" ("kind") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_963693341bd612aa01ddf3a4b6" ON "organizations" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb045b8d0047c493822a73ef5a" ON "organizations" ("clientId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "organizations_single_tethr_workspace" ON "organizations" ("kind") WHERE "kind" = 'tethr'`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "legalEntityId" uuid NOT NULL, "name" character varying(256) NOT NULL, "timezone" character varying(64), "countryCode" character varying(2), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf3c1c271638b4782216853a" ON "locations" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "legal_entities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(256) NOT NULL, "registrationNumber" character varying(64), "countryCode" character varying(2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', CONSTRAINT "PK_957140fc9f028601347fbe28f89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bcc51e0d87107e49094d5aa107" ON "legal_entities" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "cost_centers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "code" character varying(64) NOT NULL, "name" character varying(256) NOT NULL, CONSTRAINT "PK_e70f55c677c255c1f81f0ed1ccb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4cdd32414b7850ec5ec4395661" ON "cost_centers" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_680eff5fe67264d3d9ed644baf" ON "cost_centers" ("organizationId", "code") `);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(256) NOT NULL, "parentDepartmentId" uuid, "costCenterId" uuid, "headEmployeeId" uuid, CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c12b32b01521c1c3595a55b10" ON "departments" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d4c3cf55a590015ceee33241c" ON "departments" ("organizationId", "name") `);
        await queryRunner.query(`CREATE TABLE "leave_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(64) NOT NULL, "code" character varying(32) NOT NULL, "unit" character varying(8) NOT NULL DEFAULT 'day', "paid" boolean NOT NULL DEFAULT true, "requiresApproval" boolean NOT NULL DEFAULT true, "defaultAnnualEntitlement" numeric(7,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_359223e0755d19711813cd07394" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_18aee2c2b026240b3082e0e92d" ON "leave_types" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0ee9c2357f2bbd5faa136b2a2c" ON "leave_types" ("organizationId", "code") `);
        await queryRunner.query(`CREATE TABLE "leave_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "leaveTypeId" uuid NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "dayCount" numeric(7,2) NOT NULL, "reason" character varying(500), "status" character varying(16) NOT NULL DEFAULT 'pending', "approvalRequestId" uuid, "decidedByUserId" uuid, "decisionNote" text, CONSTRAINT "PK_d3abcf9a16cef1450129e06fa9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_26601600bfad52a7935b68c80c" ON "leave_requests" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_586f799e09d59ab30e55ef47f1" ON "leave_requests" ("organizationId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9ed6f8f424ec8670830c7ac76" ON "leave_requests" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "leave_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "leaveTypeId" uuid NOT NULL, "periodYear" integer NOT NULL, "entitledDays" numeric(7,2) NOT NULL DEFAULT '0', "usedDays" numeric(7,2) NOT NULL DEFAULT '0', "pendingDays" numeric(7,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_a1d90dff48fb2bfd23a7163d077" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a12a0d264dc1d458597ea727e4" ON "leave_balances" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_06587091883482c332ef5289ad" ON "leave_balances" ("organizationId", "employeeId", "leaveTypeId", "periodYear") `);
        await queryRunner.query(`CREATE TABLE "holidays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "calendarId" uuid NOT NULL, "date" date NOT NULL, "name" character varying(128) NOT NULL, CONSTRAINT "PK_3646bdd4c3817d954d830881dfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_47c9ac465d67fdb60f290b17c9" ON "holidays" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2de4944164e91de819244d8602" ON "holidays" ("organizationId", "calendarId", "date") `);
        await queryRunner.query(`CREATE TABLE "holiday_calendars" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(128) NOT NULL, "countryCode" character varying(2), CONSTRAINT "PK_e600f14506faa4edb8be8c40b12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4bfa1a43c330ff11af08d6c39e" ON "holiday_calendars" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2703d3ea1cb5cc6487c1081401" ON "holiday_calendars" ("organizationId", "name") `);
        await queryRunner.query(`CREATE TABLE "employee_leave_entitlements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "validFrom" date NOT NULL, "validTo" date, "employeeId" uuid NOT NULL, "leaveTypeId" uuid NOT NULL, "annualEntitlement" numeric(7,2) NOT NULL, "updatedByUserId" uuid, CONSTRAINT "PK_6b08001b87d1cc96d6ed439d81c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_716f32890a317eee9aea76a8f9" ON "employee_leave_entitlements" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_841bf67abf1bb3bcc9033f0255" ON "employee_leave_entitlements" ("validFrom") `);
        await queryRunner.query(`CREATE INDEX "IDX_c29c899f2abb71a7414acb2654" ON "employee_leave_entitlements" ("organizationId", "employeeId", "leaveTypeId") `);
        await queryRunner.query(`CREATE TABLE "form_upload_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "formId" uuid NOT NULL, "fieldKey" character varying(64) NOT NULL, "storageKey" character varying(512) NOT NULL, "contentType" character varying(128) NOT NULL, "sizeBytes" bigint NOT NULL DEFAULT '0', "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "usedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e0ba10f7e24b68120badf068eef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c51442b9adaa63b6ee1f463e88" ON "form_upload_tickets" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_86cd56a7d5532d997dff6e5555" ON "form_upload_tickets" ("organizationId", "storageKey") `);
        await queryRunner.query(`CREATE TABLE "form_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "formId" uuid NOT NULL, "answers" jsonb NOT NULL DEFAULT '{}', "files" jsonb NOT NULL DEFAULT '[]', "status" character varying(16) NOT NULL DEFAULT 'pending', "statusReason" text, "submittedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "targetRefType" character varying(32), "targetRefId" uuid, CONSTRAINT "PK_fb6e1e9f26cda31c358a8a1530e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f0e661b9f4c389f40399337be" ON "form_submissions" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16a7a94cfe7aa37aa3c06dac3c" ON "form_submissions" ("organizationId", "formId") `);
        await queryRunner.query(`CREATE TABLE "form_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(200) NOT NULL, "slug" character varying(200) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'draft', "target" character varying(32) NOT NULL DEFAULT 'generic', CONSTRAINT "PK_e7b46c89a49ab24f30618b410d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe1e30c15da1373cd2de7028a9" ON "form_definitions" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_24939d83ea9bfe0d00dd5044e3" ON "form_definitions" ("organizationId", "slug") `);
        await queryRunner.query(`CREATE TABLE "tax_slab_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(128) NOT NULL, "financialYearLabel" character varying(32) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'PKR', "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_39ea08e960732fdff7a8a6eca0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a4ca426f0dd39cb47c8a3b68c5" ON "tax_slab_groups" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5ec07244c7d53324a221e82a63" ON "tax_slab_groups" ("organizationId", "name") `);
        await queryRunner.query(`CREATE TABLE "tax_slabs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "groupId" uuid NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "upperBound" numeric(14,2), "ratePercent" numeric(7,4) NOT NULL, "flatAdditive" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_9138b80c90b7096dbbd9b43d6aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_155ed05efaa623f08fe69c30f0" ON "tax_slabs" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5247d3d68e52680a021fd46d7c" ON "tax_slabs" ("organizationId", "groupId") `);
        await queryRunner.query(`CREATE TABLE "form_fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "formId" uuid NOT NULL, "fieldKey" character varying(64) NOT NULL, "label" character varying(200) NOT NULL, "type" character varying(16) NOT NULL, "required" boolean NOT NULL DEFAULT false, "options" jsonb NOT NULL DEFAULT '[]', "sortOrder" integer NOT NULL DEFAULT '0', "mapsTo" character varying(64), "helpText" text, CONSTRAINT "PK_dc4b73290f2926c3a7d7c92d1e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb16741d70675ef8168dfcbf43" ON "form_fields" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b392002a85ff9a31535493bb00" ON "form_fields" ("organizationId", "formId", "fieldKey") `);
        await queryRunner.query(`CREATE TABLE "payslips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "runId" uuid NOT NULL, "employeeId" uuid NOT NULL, "payslipNumber" character varying(32) NOT NULL, "periodYear" integer NOT NULL, "periodMonth" integer NOT NULL, "payDate" date NOT NULL, "currency" character varying(3) NOT NULL, "employeeNumber" character varying(32) NOT NULL, "employeeName" character varying(257) NOT NULL, "roleTitle" character varying(160), "hireDate" date NOT NULL, "paidDays" numeric(7,2) NOT NULL, "lopDays" numeric(7,2) NOT NULL DEFAULT '0', "standardWorkingDays" integer NOT NULL DEFAULT '0', "grossAmount" numeric(14,2) NOT NULL, "taxableAmount" numeric(14,2) NOT NULL, "incomeTaxAmount" numeric(14,2) NOT NULL, "netPayAmount" numeric(14,2) NOT NULL, "notes" character varying(500), CONSTRAINT "PK_2b1cd07059daf60cc440c9976e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e40cc80cf17ca3e62a1646d00c" ON "payslips" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cc2e5b76e5775b45fbcc06b2d7" ON "payslips" ("organizationId", "employeeId", "periodYear", "periodMonth") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69050f4b4678fb99431cce562" ON "payslips" ("organizationId", "runId") `);
        await queryRunner.query(`CREATE TABLE "payroll_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "periodYear" integer NOT NULL, "periodMonth" integer NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'draft', "currency" character varying(3) NOT NULL DEFAULT 'PKR', "standardWorkingDays" integer NOT NULL, "holidayCalendarId" uuid, "finalizedAt" TIMESTAMP WITH TIME ZONE, "finalizedByUserId" uuid, "finalizeOverrideReason" character varying(500), "isStale" boolean NOT NULL DEFAULT false, "staleReason" character varying(500), CONSTRAINT "PK_6049f42c972640c0eb99ba8035e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52b0727deda978aaf3e372e5be" ON "payroll_runs" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e7b927b9a68fcca6435c6415c5" ON "payroll_runs" ("organizationId", "periodYear", "periodMonth") `);
        await queryRunner.query(`CREATE TABLE "payslip_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "payslipId" uuid NOT NULL, "componentCode" character varying(32) NOT NULL, "componentName" character varying(64) NOT NULL, "category" character varying(32) NOT NULL, "taxable" boolean NOT NULL, "dependsOnPaymentDays" boolean NOT NULL DEFAULT true, "defaultAmount" numeric(14,2), "amount" numeric(14,2) NOT NULL, "sourceType" character varying(32), "sourceId" uuid, "sortOrder" integer NOT NULL, CONSTRAINT "PK_e2318c56871094d11383dd2ce42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9557111b15ed96f82452b5c640" ON "payslip_lines" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_261dbd65ca969499ebf9e83541" ON "payslip_lines" ("organizationId", "payslipId") `);
        await queryRunner.query(`CREATE TABLE "payroll_run_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "runId" uuid NOT NULL, "employeeId" uuid NOT NULL, "payableDays" numeric(7,2) NOT NULL, "lopDays" numeric(7,2) NOT NULL DEFAULT '0', "standardWorkingDays" integer NOT NULL DEFAULT '0', "grossAmount" numeric(14,2) NOT NULL, "taxOverrideAmount" numeric(14,2), "note" character varying(500), CONSTRAINT "PK_de3ead8581176205f25f7107126" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b64ffc1bff82ba9b254851fb2f" ON "payroll_run_lines" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cd7ddce2f35278e50fe142edac" ON "payroll_run_lines" ("organizationId", "runId", "employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3b7c7818ff13109fdc5ccf4f4" ON "payroll_run_lines" ("organizationId", "runId") `);
        await queryRunner.query(`CREATE TABLE "payroll_run_line_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "lineId" uuid NOT NULL, "componentCode" character varying(32) NOT NULL, "componentName" character varying(64) NOT NULL, "category" character varying(32) NOT NULL, "taxable" boolean NOT NULL, "dependsOnPaymentDays" boolean NOT NULL DEFAULT true, "defaultAmount" numeric(14,2), "amount" numeric(14,2) NOT NULL, "sourceType" character varying(32), "sourceId" uuid, "sortOrder" integer NOT NULL, CONSTRAINT "PK_39b520cf98865bae64de3555a31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b9761687a30008f79ad9efc50" ON "payroll_run_line_components" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_468483faf16141e31cd91dd0c9" ON "payroll_run_line_components" ("organizationId", "lineId") `);
        await queryRunner.query(`CREATE TABLE "final_settlements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "terminationDate" date NOT NULL, "periodYear" integer NOT NULL, "periodMonth" integer NOT NULL, "currency" character varying(3) NOT NULL, "standardWorkingDays" integer NOT NULL, "workedDays" numeric(7,2) NOT NULL, "proRatedEarnings" numeric(14,2) NOT NULL, "adjustmentEarnings" numeric(14,2) NOT NULL DEFAULT '0', "leaveBalanceDays" numeric(7,2) NOT NULL, "leaveEncashmentAmount" numeric(14,2) NOT NULL, "recoveryAmount" numeric(14,2) NOT NULL, "payableTotal" numeric(14,2) NOT NULL, "taxableAmount" numeric(14,2) NOT NULL DEFAULT '0', "incomeTaxAmount" numeric(14,2) NOT NULL DEFAULT '0', "netPayableAmount" numeric(14,2) NOT NULL DEFAULT '0', "status" character varying(16) NOT NULL DEFAULT 'computed', "computedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "note" character varying(500), CONSTRAINT "PK_5f589ffe8da6ad0300251403807" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_778382efa85b5da2078c6d76d5" ON "final_settlements" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_71628ee90bafaae22386247f9b" ON "final_settlements" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "exchange_rates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "validFrom" date NOT NULL, "validTo" date, "baseCurrency" character varying(3) NOT NULL, "quoteCurrency" character varying(3) NOT NULL, "rate" numeric(18,8) NOT NULL, CONSTRAINT "PK_33a614bad9e61956079d817ebe2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_399a8642d4bf85ca0437fcce39" ON "exchange_rates" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa73b5f8195b24ab800da05cf2" ON "exchange_rates" ("validFrom") `);
        await queryRunner.query(`CREATE INDEX "IDX_73be681646990c4ad6b886ecc2" ON "exchange_rates" ("organizationId", "baseCurrency", "quoteCurrency", "validFrom") `);
        await queryRunner.query(`CREATE TABLE "salary_structures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(64) NOT NULL, "code" character varying(32) NOT NULL, "gradeId" uuid, "defaultAnnualAmount" numeric(14,2), "currency" character varying(3) NOT NULL, "payFrequency" character varying(16) NOT NULL DEFAULT 'monthly', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_1800f745fd1ebe08981cd422acd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf93b45b16a8996ea8d79c6c75" ON "salary_structures" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5bb2493c0604886e69c67a55c2" ON "salary_structures" ("organizationId", "code") `);
        await queryRunner.query(`CREATE TABLE "salary_structure_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "structureId" uuid NOT NULL, "componentId" uuid NOT NULL, "calcType" character varying(24) NOT NULL, "value" numeric(14,4) NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_85e966de274177e2f1984340562" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_851d154ce861f16ee99dea6b68" ON "salary_structure_components" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_64bbbfc5284dc0865859237ed6" ON "salary_structure_components" ("organizationId", "structureId") `);
        await queryRunner.query(`CREATE TABLE "pay_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(64) NOT NULL, "code" character varying(32) NOT NULL, "category" character varying(32) NOT NULL, "taxable" boolean NOT NULL DEFAULT true, "recurring" boolean NOT NULL DEFAULT true, "dependsOnPaymentDays" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b9a9d166f278ae52e974ce2d23b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_57f6423a71156c062c6f4eb5ab" ON "pay_components" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9724f8bf88733d516ffec75d51" ON "pay_components" ("organizationId", "code") `);
        await queryRunner.query(`CREATE TABLE "pay_adjustments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "componentId" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "currency" character varying(3) NOT NULL, "periodYear" integer NOT NULL, "periodMonth" integer NOT NULL, "kind" character varying(32) NOT NULL, "sourceType" character varying(32), "sourceId" uuid, "overwritesStructureAmount" boolean NOT NULL DEFAULT false, "isRecurring" boolean NOT NULL DEFAULT false, "recurringFrom" date, "recurringTo" date, "note" character varying(300), CONSTRAINT "PK_f9ebd8b70357bb02afced93a6a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aebf6258d61a91e8fb38a57bce" ON "pay_adjustments" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f99d4c9e630e761c6c7b33a3e5" ON "pay_adjustments" ("organizationId", "employeeId", "periodYear", "periodMonth") `);
        await queryRunner.query(`CREATE TABLE "salary_revisions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "validFrom" date NOT NULL, "validTo" date, "employeeId" uuid NOT NULL, "salaryStructureId" uuid NOT NULL, "currency" character varying(3) NOT NULL, "annualAmount" numeric(14,2) NOT NULL, "reason" character varying(32) NOT NULL, "approvedByUserId" uuid, "note" character varying(300), CONSTRAINT "PK_56b80c606d602bec1010ebf9c9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b57d54d61e6f01033e15b84d15" ON "salary_revisions" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9be892058ec6743fdaf7c2bf88" ON "salary_revisions" ("validFrom") `);
        await queryRunner.query(`CREATE INDEX "IDX_86ca821385747033fa215d510c" ON "salary_revisions" ("organizationId", "employeeId", "validFrom") `);
        await queryRunner.query(`CREATE TABLE "bonus_awards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "awardDate" date NOT NULL, "currency" character varying(3) NOT NULL, "amount" numeric(14,2) NOT NULL, "reason" character varying(32) NOT NULL, "awardedByUserId" uuid NOT NULL, "approvedByUserId" uuid, "note" character varying(500), CONSTRAINT "PK_aeb452f77e84b88b26c4341386f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d307dc9fbd553beb28481b83be" ON "bonus_awards" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_858b075a4c72e0b8d3e6e136b4" ON "bonus_awards" ("organizationId", "employeeId", "awardDate") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "groupId" uuid NOT NULL, "type" character varying(16) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'draft', "serviceYear" integer NOT NULL, "serviceMonth" integer NOT NULL, "periodStart" date NOT NULL, "periodEndExclusive" date NOT NULL, "number" character varying(32), "issueDate" date, "dueDate" date, "currency" character varying(3) NOT NULL DEFAULT 'USD', "receiverName" character varying(200), "receiverAddress" character varying(300), "receiverEmail" character varying(320), "receiverPhone" character varying(50), "receiverZipCode" character varying(20), "receiverCity" character varying(80), "receiverCountry" character varying(80), "subTotal" numeric(14,2) NOT NULL DEFAULT '0.00', "totalAmount" numeric(14,2) NOT NULL DEFAULT '0.00', "paidAt" TIMESTAMP WITH TIME ZONE, "paymentReference" character varying(120), "sourcePayrollRunId" uuid, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4237f4b816fec1df81bd85f833" ON "invoices" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "invoices_org_status_idx" ON "invoices" ("organizationId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "invoices_org_group_type_period_unique" ON "invoices" ("organizationId", "groupId", "type", "serviceYear", "serviceMonth") `);
        await queryRunner.query(`CREATE TABLE "invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "invoiceId" uuid NOT NULL, "kind" character varying(16) NOT NULL, "employeeId" uuid, "employeeName" character varying(257), "monthLabel" character varying(32), "description" character varying(200) NOT NULL, "quantity" numeric(14,2) NOT NULL DEFAULT '1', "unitPrice" numeric(14,2) NOT NULL, "total" numeric(14,2) NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_3d18eb48142b916f581f0c21a65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c905ef195ecec44d4102d5bff8" ON "invoice_lines" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "invoice_lines_org_invoice_idx" ON "invoice_lines" ("organizationId", "invoiceId") `);
        await queryRunner.query(`CREATE TABLE "client_billing_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "feeAmount" numeric(14,2) NOT NULL DEFAULT '300.00', "feeCurrency" character varying(3) NOT NULL DEFAULT 'USD', "paymentTermsNetDays" integer NOT NULL DEFAULT '7', "anchorDay" integer NOT NULL DEFAULT '20', "receiverName" character varying(200), "receiverAddress" character varying(300), "receiverEmail" character varying(320), "receiverPhone" character varying(50), "receiverZipCode" character varying(20), "receiverCity" character varying(80), "receiverCountry" character varying(80), "senderName" character varying(200), "senderAddress" character varying(300), "senderEmail" character varying(320), "senderPhone" character varying(50), "senderZipCode" character varying(20), "senderCity" character varying(80), "senderCountry" character varying(80), "invoiceLogoDataUrl" text, "signatureDataUrl" text, "bankName" character varying(160), "bankAccountName" character varying(160), "bankAccountNumber" character varying(80), "bankSwift" character varying(32), CONSTRAINT "PK_788571a7a372c3abb7a99cbd57a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bea576239dc7ce5d9f5764bc9a" ON "client_billing_configs" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "client_billing_configs_org_unique" ON "client_billing_configs" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "billing_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying(64) NOT NULL, "servicesPrefix" character varying(8) NOT NULL DEFAULT 'SP', "expensesPrefix" character varying(8) NOT NULL DEFAULT 'EP', CONSTRAINT "PK_45a37d0317d12f23ba5432e15af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b7764463d9dd0eebcf4abd2e23" ON "billing_groups" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "billing_groups_org_name_unique" ON "billing_groups" ("organizationId", "name") `);
        await queryRunner.query(`CREATE TABLE "billing_group_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "validFrom" date NOT NULL, "validTo" date, "employeeId" uuid NOT NULL, "groupId" uuid NOT NULL, "monthlyRate" numeric(14,2) NOT NULL, "rateCurrency" character varying(3) NOT NULL DEFAULT 'USD', CONSTRAINT "PK_7d69d82e26d56bb1c28c8ee3113" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fca4aa995238f8379ce115bba6" ON "billing_group_members" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf75a852c5e72ae18a5c4cfc45" ON "billing_group_members" ("validFrom") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "billing_members_org_emp_open_unique" ON "billing_group_members" ("organizationId", "employeeId") WHERE "validTo" IS NULL`);
        await queryRunner.query(`CREATE INDEX "billing_members_org_group_idx" ON "billing_group_members" ("organizationId", "groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba2872695d25fd5218539be4a8" ON "billing_group_members" ("organizationId", "employeeId", "validFrom") `);
        await queryRunner.query(`CREATE TABLE "employee_feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "submittedByUserId" uuid NOT NULL, "category" character varying(24) NOT NULL DEFAULT 'general', "subject" character varying(160) NOT NULL, "body" text NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'submitted', "resolvedByUserId" uuid, "resolutionNote" text, CONSTRAINT "PK_76e65afdd3903f652bf424031b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a304c5a1ab77ca0ad7e5d87ed9" ON "employee_feedback" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_392de95305c270b65536de2646" ON "employee_feedback" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0962e3978cad28e7a0b625e367" ON "employee_feedback" ("organizationId", "status") `);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "title" character varying(200) NOT NULL, "body" text NOT NULL, "audience" character varying(16) NOT NULL DEFAULT 'all', "isPinned" boolean NOT NULL DEFAULT false, "publishedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE, "publishedByUserId" uuid NOT NULL, CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f7aad9ecbc4e6f88f1a092c6b" ON "announcements" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a4e1060efea3a6340fe705b89" ON "announcements" ("organizationId", "audience", "publishedAt") `);
        await queryRunner.query(`CREATE TABLE "employee_hr_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "roleTitle" character varying(160), "salaryBreakdown" text, "paymentMode" character varying(16), "bankName" character varying(160), "bankAccountTitle" character varying(160), "bankAccountNumber" character varying(80), "bankIban" character varying(80), "hardwareInfo" text, "employeeRecordForm" text, "updatedByUserId" uuid, CONSTRAINT "PK_38a3a97d88c6168c558a3cc80de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5d5cda7f3724cd327c74d91061" ON "employee_hr_records" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4887aa4aa06f23ff7aaae6b301" ON "employee_hr_records" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "employee_onboarding_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "taskKey" character varying(40) NOT NULL, "title" character varying(160) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'notStarted', "dueDate" date, "completedAt" TIMESTAMP WITH TIME ZONE, "completedByUserId" uuid, "notes" text, "updatedByUserId" uuid, CONSTRAINT "PK_ce7f741720cc6e85915108fbdb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f0a88fcd9ba7ecfd4f4d94a54" ON "employee_onboarding_tasks" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b009fd64be4f871751b30594b8" ON "employee_onboarding_tasks" ("organizationId", "employeeId", "taskKey") `);
        await queryRunner.query(`CREATE TABLE "employee_document_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "documentId" uuid NOT NULL, "category" character varying(24) NOT NULL, "visibility" character varying(16) NOT NULL DEFAULT 'tethr', "attachedByUserId" uuid NOT NULL, CONSTRAINT "PK_149e414ac6a4c99e52a9384a977" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f91453332eac20df56bff559eb" ON "employee_document_links" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e59c4a94192e2a497cd17cede" ON "employee_document_links" ("organizationId", "visibility") `);
        await queryRunner.query(`CREATE INDEX "IDX_0657f57dd43fd29dc5cf210487" ON "employee_document_links" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "employee_assessments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "title" character varying(160) NOT NULL, "assessmentDate" date NOT NULL, "score" integer, "assessorName" character varying(160), "notes" text, "createdByUserId" uuid NOT NULL, CONSTRAINT "PK_e4c85d1ecd9a83de72f5a7edf13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd58ec603dbf6bbc331e168ea9" ON "employee_assessments" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2b8afd2311d6781e9c58fec10" ON "employee_assessments" ("organizationId", "employeeId", "assessmentDate") `);
        await queryRunner.query(`CREATE TABLE "bank_detail_change_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "bankName" character varying(160), "bankAccountTitle" character varying(160), "bankAccountNumber" character varying(80), "bankIban" character varying(80), "status" character varying(16) NOT NULL DEFAULT 'pending', "approvalRequestId" uuid, "requestedByUserId" uuid, "decidedByUserId" uuid, "decidedAt" TIMESTAMP WITH TIME ZONE, "decisionNote" character varying(300), CONSTRAINT "PK_a39a2a8eb41d1140d1e204ada40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b31dfa3f170297c18937ba390" ON "bank_detail_change_requests" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd79c87d5de258b5f472e61298" ON "bank_detail_change_requests" ("organizationId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_65acf072cbcf6fb084227beba6" ON "bank_detail_change_requests" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeNumber" character varying(32) NOT NULL, "firstName" character varying(128) NOT NULL, "middleName" character varying(128), "lastName" character varying(128) NOT NULL, "salutation" character varying(16), "workEmail" character varying(320), "roleTitle" character varying(160), "dateOfBirth" date, "probationEndDate" date, "hireDate" date NOT NULL, "scheduledConfirmationDate" date, "finalConfirmationDate" date, "contractEndDate" date, "noticePeriodDays" integer, "retirementDate" date, "holidayCalendarId" uuid, "terminationDate" date, "employmentStatus" character varying(16) NOT NULL DEFAULT 'active', "workerType" character varying(16) NOT NULL DEFAULT 'permanent', CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_abdeaa85e3452405517863b5a2" ON "employees" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3740b2377293d8ff10ff5ccccf" ON "employees" ("organizationId", "employeeNumber") `);
        await queryRunner.query(`CREATE TABLE "employee_work_histories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "companyName" character varying(256) NOT NULL, "designation" character varying(160), "salary" numeric(12,2), "address" character varying(512), "contact" character varying(160), "totalExperience" character varying(64), "createdByUserId" uuid, "updatedByUserId" uuid, CONSTRAINT "PK_947bf5b10ff692928c4c0f957ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_114812322c16ac969040453b6e" ON "employee_work_histories" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_70952f6386487c2ccb26475c37" ON "employee_work_histories" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "employee_separations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "type" character varying(16) NOT NULL, "resignationLetterDate" date, "relievingDate" date, "reasonForLeaving" text, "leaveEncashed" boolean NOT NULL DEFAULT false, "encashmentDate" date, "heldOn" date, "newWorkplace" character varying(256), "feedback" text, "initiatedByUserId" uuid, CONSTRAINT "PK_5d1823799e39fd036e91c4705b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_30c71fedb61639150c42d297c1" ON "employee_separations" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b2fe2da1b3994c1c423be21451" ON "employee_separations" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "employee_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "photoUrl" text, "personalEmail" character varying(320), "phone" character varying(48), "addressLine1" character varying(200), "addressLine2" character varying(200), "city" character varying(128), "region" character varying(128), "countryCode" character varying(2), "postalCode" character varying(24), "permanentAddressLine1" character varying(200), "permanentAddressLine2" character varying(200), "permanentCity" character varying(128), "permanentRegion" character varying(128), "permanentCountryCode" character varying(2), "permanentPostalCode" character varying(24), "currentAccommodationType" character varying(16), "permanentAccommodationType" character varying(16), "preferredContactChannel" character varying(16), "emergencyContactName" character varying(160), "emergencyContactPhone" character varying(48), "emergencyContactRelation" character varying(48), "updatedByUserId" uuid, CONSTRAINT "PK_8481c6a4516f6589b23adf7fefa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40942d52669a738f3e6cd725fc" ON "employee_profiles" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e1d96fbab150496f6f00896aa8" ON "employee_profiles" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "employee_personal_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "passportNumber" character varying(64), "passportIssueDate" date, "passportIssuePlace" character varying(128), "passportValidUpto" date, "maritalStatus" character varying(16), "bloodGroup" character varying(8), "familyBackground" text, "healthDetails" text, "bio" text, "updatedByUserId" uuid, CONSTRAINT "PK_45c1de779ed4e0a369f1d14e04f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_208421a6fb1947dff0d03b58c0" ON "employee_personal_details" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6dcf71343f93aac922cfe5f85c" ON "employee_personal_details" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "employee_offboarding_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "separationId" uuid, "taskKey" character varying(40) NOT NULL, "title" character varying(160) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'notStarted', "dueDate" date, "completedAt" TIMESTAMP WITH TIME ZONE, "completedByUserId" uuid, "notes" text, "updatedByUserId" uuid, CONSTRAINT "PK_13cde247e3c7a1a6df343cc6467" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_057f59908284cf38fb6a91e614" ON "employee_offboarding_tasks" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f388ec123ed0c6f77c08c80080" ON "employee_offboarding_tasks" ("organizationId", "employeeId", "taskKey") `);
        await queryRunner.query(`CREATE TABLE "employee_exit_interviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "separationId" uuid NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "scheduledDate" date, "interviewerUserIdsJson" text, "summary" text, "finalDecision" character varying(16), "updatedByUserId" uuid, CONSTRAINT "PK_fe1c99c4514d7ce4efa75a86c6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc9dd740633194e7f6c7b99513" ON "employee_exit_interviews" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_880c70bfcbdf72b59ba0f7eaf7" ON "employee_exit_interviews" ("organizationId", "separationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc99dbfd068e053bb1d4526d76" ON "employee_exit_interviews" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(256) NOT NULL, CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_educations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "schoolOrUniversity" character varying(256) NOT NULL, "qualification" character varying(256) NOT NULL, "level" character varying(16) NOT NULL, "yearOfPassing" integer, "classOrPercentage" character varying(64), "majorSubjects" character varying(256), "createdByUserId" uuid, "updatedByUserId" uuid, CONSTRAINT "PK_3755bc5568c47c9cd8ed2d468b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0df5879946294ccc5e61487617" ON "employee_educations" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_01cf7f67440bdfa31101b27501" ON "employee_educations" ("organizationId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE "timesheets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'open', "totalHours" numeric(7,2) NOT NULL DEFAULT '0', "submittedByUserId" uuid, "approvedByUserId" uuid, CONSTRAINT "PK_1dc280b68c9353ecce41a34be71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92deead29242681cd31ca5e9d8" ON "timesheets" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1e49bc9ab2824f0803b9b06cd0" ON "timesheets" ("organizationId", "employeeId", "periodStart") `);
        await queryRunner.query(`CREATE TABLE "time_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "date" date NOT NULL, "hours" numeric(5,2) NOT NULL, "source" character varying(16) NOT NULL DEFAULT 'clock', "note" character varying(300), CONSTRAINT "PK_b8bc5f10269ba2fe88708904aa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_da9f77b7b6d2ede0a80d853cbf" ON "time_entries" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_737a9d30a60604a5c57f339758" ON "time_entries" ("organizationId", "employeeId", "date") `);
        await queryRunner.query(`CREATE TABLE "clock_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "type" character varying(8) NOT NULL, "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, "source" character varying(16) NOT NULL DEFAULT 'web', CONSTRAINT "PK_08ee1d588f22ec11fc7771c6a87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb87a51d1f41a427c153880825" ON "clock_events" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_94f521f8d7b9dd9d74c2b62027" ON "clock_events" ("organizationId", "employeeId", "occurredAt") `);
        await queryRunner.query(`CREATE TABLE "regularizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "employeeId" uuid NOT NULL, "date" date NOT NULL, "requestedHours" numeric(5,2) NOT NULL, "reason" character varying(300) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', CONSTRAINT "PK_51882a1b9f885cb7d82d596f243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ccb0806323c2ffdf03436e0363" ON "regularizations" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_31ca71f3764264c3287c5ea324" ON "regularizations" ("organizationId", "employeeId", "date") `);
        await queryRunner.query(`CREATE TABLE "assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "validFrom" date NOT NULL, "validTo" date, "employeeId" uuid NOT NULL, "positionId" uuid NOT NULL, "assignmentType" character varying(16) NOT NULL DEFAULT 'primary', "reportsToEmployeeId" uuid, "isPrimary" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_869018c910d5ae1bc521e0e29f" ON "assignments" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_40794b8a4b49cb47cd0eebaf09" ON "assignments" ("validFrom") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e7d24141a5be50b7f1fe35d1b" ON "assignments" ("organizationId", "employeeId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_0e7d24141a5be50b7f1fe35d1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40794b8a4b49cb47cd0eebaf09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_869018c910d5ae1bc521e0e29f"`);
        await queryRunner.query(`DROP TABLE "assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31ca71f3764264c3287c5ea324"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccb0806323c2ffdf03436e0363"`);
        await queryRunner.query(`DROP TABLE "regularizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94f521f8d7b9dd9d74c2b62027"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb87a51d1f41a427c153880825"`);
        await queryRunner.query(`DROP TABLE "clock_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_737a9d30a60604a5c57f339758"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da9f77b7b6d2ede0a80d853cbf"`);
        await queryRunner.query(`DROP TABLE "time_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e49bc9ab2824f0803b9b06cd0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92deead29242681cd31ca5e9d8"`);
        await queryRunner.query(`DROP TABLE "timesheets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01cf7f67440bdfa31101b27501"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0df5879946294ccc5e61487617"`);
        await queryRunner.query(`DROP TABLE "employee_educations"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc99dbfd068e053bb1d4526d76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_880c70bfcbdf72b59ba0f7eaf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc9dd740633194e7f6c7b99513"`);
        await queryRunner.query(`DROP TABLE "employee_exit_interviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f388ec123ed0c6f77c08c80080"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_057f59908284cf38fb6a91e614"`);
        await queryRunner.query(`DROP TABLE "employee_offboarding_tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6dcf71343f93aac922cfe5f85c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_208421a6fb1947dff0d03b58c0"`);
        await queryRunner.query(`DROP TABLE "employee_personal_details"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1d96fbab150496f6f00896aa8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40942d52669a738f3e6cd725fc"`);
        await queryRunner.query(`DROP TABLE "employee_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2fe2da1b3994c1c423be21451"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30c71fedb61639150c42d297c1"`);
        await queryRunner.query(`DROP TABLE "employee_separations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70952f6386487c2ccb26475c37"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_114812322c16ac969040453b6e"`);
        await queryRunner.query(`DROP TABLE "employee_work_histories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3740b2377293d8ff10ff5ccccf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abdeaa85e3452405517863b5a2"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65acf072cbcf6fb084227beba6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd79c87d5de258b5f472e61298"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b31dfa3f170297c18937ba390"`);
        await queryRunner.query(`DROP TABLE "bank_detail_change_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2b8afd2311d6781e9c58fec10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd58ec603dbf6bbc331e168ea9"`);
        await queryRunner.query(`DROP TABLE "employee_assessments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0657f57dd43fd29dc5cf210487"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e59c4a94192e2a497cd17cede"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f91453332eac20df56bff559eb"`);
        await queryRunner.query(`DROP TABLE "employee_document_links"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b009fd64be4f871751b30594b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f0a88fcd9ba7ecfd4f4d94a54"`);
        await queryRunner.query(`DROP TABLE "employee_onboarding_tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4887aa4aa06f23ff7aaae6b301"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d5cda7f3724cd327c74d91061"`);
        await queryRunner.query(`DROP TABLE "employee_hr_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a4e1060efea3a6340fe705b89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f7aad9ecbc4e6f88f1a092c6b"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0962e3978cad28e7a0b625e367"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_392de95305c270b65536de2646"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a304c5a1ab77ca0ad7e5d87ed9"`);
        await queryRunner.query(`DROP TABLE "employee_feedback"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba2872695d25fd5218539be4a8"`);
        await queryRunner.query(`DROP INDEX "public"."billing_members_org_group_idx"`);
        await queryRunner.query(`DROP INDEX "public"."billing_members_org_emp_open_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf75a852c5e72ae18a5c4cfc45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fca4aa995238f8379ce115bba6"`);
        await queryRunner.query(`DROP TABLE "billing_group_members"`);
        await queryRunner.query(`DROP INDEX "public"."billing_groups_org_name_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7764463d9dd0eebcf4abd2e23"`);
        await queryRunner.query(`DROP TABLE "billing_groups"`);
        await queryRunner.query(`DROP INDEX "public"."client_billing_configs_org_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bea576239dc7ce5d9f5764bc9a"`);
        await queryRunner.query(`DROP TABLE "client_billing_configs"`);
        await queryRunner.query(`DROP INDEX "public"."invoice_lines_org_invoice_idx"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c905ef195ecec44d4102d5bff8"`);
        await queryRunner.query(`DROP TABLE "invoice_lines"`);
        await queryRunner.query(`DROP INDEX "public"."invoices_org_group_type_period_unique"`);
        await queryRunner.query(`DROP INDEX "public"."invoices_org_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4237f4b816fec1df81bd85f833"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_858b075a4c72e0b8d3e6e136b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d307dc9fbd553beb28481b83be"`);
        await queryRunner.query(`DROP TABLE "bonus_awards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86ca821385747033fa215d510c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9be892058ec6743fdaf7c2bf88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b57d54d61e6f01033e15b84d15"`);
        await queryRunner.query(`DROP TABLE "salary_revisions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f99d4c9e630e761c6c7b33a3e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aebf6258d61a91e8fb38a57bce"`);
        await queryRunner.query(`DROP TABLE "pay_adjustments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9724f8bf88733d516ffec75d51"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57f6423a71156c062c6f4eb5ab"`);
        await queryRunner.query(`DROP TABLE "pay_components"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64bbbfc5284dc0865859237ed6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_851d154ce861f16ee99dea6b68"`);
        await queryRunner.query(`DROP TABLE "salary_structure_components"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bb2493c0604886e69c67a55c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf93b45b16a8996ea8d79c6c75"`);
        await queryRunner.query(`DROP TABLE "salary_structures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73be681646990c4ad6b886ecc2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa73b5f8195b24ab800da05cf2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_399a8642d4bf85ca0437fcce39"`);
        await queryRunner.query(`DROP TABLE "exchange_rates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71628ee90bafaae22386247f9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_778382efa85b5da2078c6d76d5"`);
        await queryRunner.query(`DROP TABLE "final_settlements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_468483faf16141e31cd91dd0c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b9761687a30008f79ad9efc50"`);
        await queryRunner.query(`DROP TABLE "payroll_run_line_components"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3b7c7818ff13109fdc5ccf4f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd7ddce2f35278e50fe142edac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b64ffc1bff82ba9b254851fb2f"`);
        await queryRunner.query(`DROP TABLE "payroll_run_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_261dbd65ca969499ebf9e83541"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9557111b15ed96f82452b5c640"`);
        await queryRunner.query(`DROP TABLE "payslip_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7b927b9a68fcca6435c6415c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52b0727deda978aaf3e372e5be"`);
        await queryRunner.query(`DROP TABLE "payroll_runs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69050f4b4678fb99431cce562"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc2e5b76e5775b45fbcc06b2d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e40cc80cf17ca3e62a1646d00c"`);
        await queryRunner.query(`DROP TABLE "payslips"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b392002a85ff9a31535493bb00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb16741d70675ef8168dfcbf43"`);
        await queryRunner.query(`DROP TABLE "form_fields"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5247d3d68e52680a021fd46d7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_155ed05efaa623f08fe69c30f0"`);
        await queryRunner.query(`DROP TABLE "tax_slabs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ec07244c7d53324a221e82a63"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4ca426f0dd39cb47c8a3b68c5"`);
        await queryRunner.query(`DROP TABLE "tax_slab_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24939d83ea9bfe0d00dd5044e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe1e30c15da1373cd2de7028a9"`);
        await queryRunner.query(`DROP TABLE "form_definitions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16a7a94cfe7aa37aa3c06dac3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f0e661b9f4c389f40399337be"`);
        await queryRunner.query(`DROP TABLE "form_submissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86cd56a7d5532d997dff6e5555"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c51442b9adaa63b6ee1f463e88"`);
        await queryRunner.query(`DROP TABLE "form_upload_tickets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c29c899f2abb71a7414acb2654"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_841bf67abf1bb3bcc9033f0255"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_716f32890a317eee9aea76a8f9"`);
        await queryRunner.query(`DROP TABLE "employee_leave_entitlements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2703d3ea1cb5cc6487c1081401"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bfa1a43c330ff11af08d6c39e"`);
        await queryRunner.query(`DROP TABLE "holiday_calendars"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2de4944164e91de819244d8602"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47c9ac465d67fdb60f290b17c9"`);
        await queryRunner.query(`DROP TABLE "holidays"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06587091883482c332ef5289ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a12a0d264dc1d458597ea727e4"`);
        await queryRunner.query(`DROP TABLE "leave_balances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9ed6f8f424ec8670830c7ac76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_586f799e09d59ab30e55ef47f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26601600bfad52a7935b68c80c"`);
        await queryRunner.query(`DROP TABLE "leave_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ee9c2357f2bbd5faa136b2a2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18aee2c2b026240b3082e0e92d"`);
        await queryRunner.query(`DROP TABLE "leave_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d4c3cf55a590015ceee33241c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c12b32b01521c1c3595a55b10"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_680eff5fe67264d3d9ed644baf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cdd32414b7850ec5ec4395661"`);
        await queryRunner.query(`DROP TABLE "cost_centers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcc51e0d87107e49094d5aa107"`);
        await queryRunner.query(`DROP TABLE "legal_entities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf3c1c271638b4782216853a"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP INDEX "public"."organizations_single_tethr_workspace"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb045b8d0047c493822a73ef5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_963693341bd612aa01ddf3a4b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b1aee57d246d82c531016e652"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0caf5ce7c6fe569bdc8365fcf0"`);
        await queryRunner.query(`DROP TABLE "job_families"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7f38e5f23d1cfad4261802726"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ba005a1de94c4e8813351576b"`);
        await queryRunner.query(`DROP TABLE "grades"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08bdc8b939f39e6d55b4c38cfb"`);
        await queryRunner.query(`DROP TABLE "jobs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3624b2ac7912966d338ab9bc0e"`);
        await queryRunner.query(`DROP TABLE "pay_bands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f12007cfd7db4b8aa269d13e27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52017e4e4b745305eaee9313d5"`);
        await queryRunner.query(`DROP TABLE "positions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e46bba20d9b2a0a212c53c8618"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88d9e9c503051c35643ebfc49d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_630548134611c66a73c8b82bc1"`);
        await queryRunner.query(`DROP TABLE "applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9970b4876c927276e2f188e15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2593c8a7526e53ad6e424562ce"`);
        await queryRunner.query(`DROP TABLE "candidate_documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1c4b0be2767a20b4f20b04ca2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cb1c49d7ee68613e0db8bab2c"`);
        await queryRunner.query(`DROP TABLE "cv_parses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d20a7d106b7e2d197d214997a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e655dbefaba9ea137d7239f60"`);
        await queryRunner.query(`DROP TABLE "hiring_request_updates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06cb3a14600de021f89d1089b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d56a47318062e86ca2585103af"`);
        await queryRunner.query(`DROP TABLE "candidates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49195e316cc822e0166fb268e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1c0280da4d594ccdc92d45566"`);
        await queryRunner.query(`DROP TABLE "hiring_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba26b5a49c128813199d2e1bb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a96087ce438fd97173f59b72e1"`);
        await queryRunner.query(`DROP TABLE "interview_feedback"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba5e954677afd1a83b12dee215"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6e541878030a70fd8e16e0b38"`);
        await queryRunner.query(`DROP TABLE "interview_feedback_skills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d309e56d27155e455b23a1e53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cfa3b50494400d9b68eded6b3"`);
        await queryRunner.query(`DROP TABLE "interview_rounds"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_425f9fc0d8290a4d6325fc98d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bdf1b036b1da2a8443cfee6fa"`);
        await queryRunner.query(`DROP TABLE "interview_panel_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5da82c4d774cc1fcaf5d361da0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af49a547afc9d8e9f790057a9c"`);
        await queryRunner.query(`DROP TABLE "job_postings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c0f5447cbeddb1f62427d38c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cf1a0367209ecf220b3ff78bf"`);
        await queryRunner.query(`DROP TABLE "interviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0c239940681cf027f38584987"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_531330d7396291798408abcc80"`);
        await queryRunner.query(`DROP TABLE "offers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1011d56e572cb38134245cce6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af8dcab806f3298e6072e3e532"`);
        await queryRunner.query(`DROP TABLE "shortlist_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c65a0cb7235f739e2010d70999"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d08f805c2826a6a503ae3823b6"`);
        await queryRunner.query(`DROP TABLE "shortlists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b81fec571ea2be3b498f7bc96"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52601717ed17e30ae08b90993b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f2c9619322e5354049f139a3d"`);
        await queryRunner.query(`DROP TABLE "audit_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddfb7904324cdba38d3c73de93"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7191f881489123fab6c8e5273"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3d6aea8fcca58182b2e80ce97"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d27a5e69fb41256abed347a85e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c63f25e362340df593c13fb152"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0933e1dfb2993d672af1a98f08"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5297b03c43166a7a7543fda0f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0286ef461cd5bf71cd6fa29d52"`);
        await queryRunner.query(`DROP TABLE "user_role_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24fbd55f077dc6f373c0b7030c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ca925f66775b959124999155f"`);
        await queryRunner.query(`DROP TABLE "document_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f16eaa571c8fc0ee214cad0f1c"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_702a378b99f32d7a67da415f4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_698397478208a19b887d555da0"`);
        await queryRunner.query(`DROP TABLE "outbox_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30487a0b7614c9b0b3ea84b8b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3441394ea68b33d494a4de1e8"`);
        await queryRunner.query(`DROP TABLE "processed_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36db0e967a26420d3f33eeea18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f45df3f8c6cb9dc8b6573e2c2"`);
        await queryRunner.query(`DROP TABLE "approval_requests"`);
    }

}
