export const EXPENSE_CATEGORY_REPOSITORY = Symbol('EXPENSE_CATEGORY_REPOSITORY');
export const EXPENSE_CLAIM_REPOSITORY = Symbol('EXPENSE_CLAIM_REPOSITORY');
export const EXPENSE_CLAIM_LINE_REPOSITORY = Symbol('EXPENSE_CLAIM_LINE_REPOSITORY');
