export const FORM_DEFINITION_REPOSITORY = Symbol('FORM_DEFINITION_REPOSITORY');
export const FORM_FIELD_REPOSITORY = Symbol('FORM_FIELD_REPOSITORY');
export const FORM_SUBMISSION_REPOSITORY = Symbol('FORM_SUBMISSION_REPOSITORY');
