export const PAY_COMPONENT_REPOSITORY = Symbol('PAY_COMPONENT_REPOSITORY');
export const SALARY_STRUCTURE_REPOSITORY = Symbol('SALARY_STRUCTURE_REPOSITORY');
export const SALARY_STRUCTURE_COMPONENT_REPOSITORY = Symbol('SALARY_STRUCTURE_COMPONENT_REPOSITORY');
export const SALARY_REVISION_REPOSITORY = Symbol('SALARY_REVISION_REPOSITORY');
export const BONUS_AWARD_REPOSITORY = Symbol('BONUS_AWARD_REPOSITORY');
export const PAY_ADJUSTMENT_REPOSITORY = Symbol('PAY_ADJUSTMENT_REPOSITORY');
export const EMPLOYEE_TAX_PROFILE_REPOSITORY = Symbol('EMPLOYEE_TAX_PROFILE_REPOSITORY');
